
package com.cop4331.shopping_cart_app.databases;



import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.cop4331.shopping_cart_app.graphics.windowmanager.WindowManager;
import com.cop4331.shopping_cart_app.item.Item;




/**
 *
 * @author Justin Ament , Michael Mena
 */

public class ItemDB{

	private ArrayList<Item> items;
	private final String fileName = "Items.json";
	private static ItemDB INSTANCE;
	private Connection con;
	private Statement st;
	private ResultSet rs;
	
	/**
	 * 
	 */
	public ItemDB() {
		items=new ArrayList<Item>();
		connect();
		buildDb();
		
	///	if(ifFileExists()) {
		//	load();
		//}else {
		//	buildInitialDB();
		//	save();
		//}
	
		}
	
	public void connect() {
		try {
			Class.forName("oracle.jdbc.driver.OracleDriver");
			System.out.println("Success");
			String conn="";
			String user="";
			String pass="";
			File f=new File("lib/Conn.txt");
			FileReader fr=new FileReader(f);
			BufferedReader br=new BufferedReader(fr);
			String line;
			int i=0;
			
			while((line=br.readLine())!=null) {
				if(i==0) 
					conn=line;
				else if(i==1)
					user=line;
				else if(i==2)
					pass=line;
				i++;
			}
			
			br.close();
			fr.close();
			
		
			
			con=DriverManager.getConnection(conn,user, pass);
			st=con.createStatement();
			System.out.println("Connection Success");
			
		}
			
		catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public void buildDb() {
		try {
			//execute a query
			String query="select * from item";
			rs=st.executeQuery(query);
			String name;
			String description;
			int sellerID;
			int quantity;
			double price;
			double inv_price;

			while(rs.next()) {
				
				name=rs.getString("name");
				description=rs.getString("description");
				sellerID=Integer.parseInt(rs.getString("sellerID"));
				quantity=Integer.parseInt(rs.getString("quantity"));
				price=Double.parseDouble(rs.getString("price"));
				inv_price=Double.parseDouble(rs.getString("inv_price"));
				System.out.println(name+" "+description+" "+sellerID+" "+quantity+" "+price+" "+inv_price);
				Item a=new Item(name, description, sellerID, quantity, price, inv_price);
				items.add(a);
				
			}
			System.out.println("Total items: "+items.size());
		}
		catch(Exception e) {
			e.printStackTrace();
		}

		if(items.isEmpty())
			buildInitialDB();
	}
	
	
	/**
	 * @returns INSTANCE
	 */
	public static ItemDB getInstance() {
		if(INSTANCE == null) {
			synchronized(WindowManager.class) {
				if(INSTANCE == null)
					INSTANCE = new ItemDB();
			}
		}
		return INSTANCE;
	}
	
	/**
	 * Forces creates INSTANCE
	 */
	public static void init() {
		getInstance();
	}

	/**
	 * build prefab DB
	 */
	private void buildInitialDB() {
		String sql="create table item(name varchar2(15), description varchar2(30), sellerID number, quantity number, price binary_float, inv_price binary_float, id NUMBER generated by default on null as identity, PRIMARY KEY(ID))";
		try {
			st.execute(sql);
			sql="insert into item values ('default item', 'test item',0, 0, 0, 0, 0)";
			st.execute(sql);
			sql="insert into item values ('default item', 'test item',2, 100, 10.0, 8.0, null)";
			st.execute(sql);
		}
		catch(Exception e) {
			e.printStackTrace();
		}
		buildDb();
	}
	
    /**
     * @param itemID
     * @param new_quantity
     * updates the quantity of a certain item
     */
    public void setQuantity(int itemID, int new_quantity) {
    	items.get(itemID).setQuantity(new_quantity);
    	String query="update item set quantity="+Integer.toString(new_quantity)+" where id="+Integer.toString(itemID);
    	try {
    		st.execute(query);
    		
    	}
    	catch(Exception e) {
    		e.printStackTrace();
 
    	}
    }
    
    /**
     * @param id
     * @returns items from a seller
     */
    public List<Item> getItemBySeller(int id) {
    	List<Item> seller_items=new ArrayList<Item>();
    	for(int i=0; i<items.size(); i++) {
    		if(items.get(i).getSellerID()==id) seller_items.add(items.get(i));
    	}
    	return seller_items;
    }
    /**
     * @returns item list
     */
    public List<Item> getFullInventory() {
    	return items;
    }
    
    /**
     * @param itemID
     * @returns item
     */
    public Item getItem(int itemID) {
    	return items.get(itemID);
    }
    
    /**
     * @param a
     * @return itemID
     */
    public int getItemID(Item a) {
    	int value=-1;
    	for(int i=0; i<items.size(); i++) {
    		if(a==items.get(i)) value=i;
    	}
    	return value; 
    }
    
    /**
     * @param a
     * adds item to DB
     */
    public void addItem(Item a) {
    	
    	items.add(a);
    	String sql="insert into item values('"
    		+a.getName()+"', '"+a.getDescription()+"', "+(a.getSellerID())+", "+a.getQuantity()+", "+a.getPrice()+", "
    		+a.getInvPrice()+", null)";   	
    	System.out.println(sql);
    	try {
			st.execute(sql);
			System.out.println("added item");
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	
    	//save(); <--- too slow
    }
	
	
	/**
	 * @returns true if file exists
	 */
	private boolean ifFileExists() {
		return new File(fileName).exists();
	}

	public void close() {
		// TODO Auto-generated method stub
		try {
			System.out.println("Closing item connections...");
			rs.close();
			st.close();
			con.close();
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
	}
	 
	


}

